title: İsa Alp
author: GitHub User
email: isa@isaalp.com
description: >
  "isa,alp,isa alp,hello,turkey"
baseurl: "/minimaless" # the subpath of your site, e.g. /blog
url: "http://isaalp.com/minimaless" # the base hostname & protocol for your site, e.g. http://example.com

website: http://isaalp.com
github_username:  1
linkedin_username: 1
twitter_username: 1
facebook_username: 1
keybase_username: 1

# use Font Awesome icon names http://fontawesome.io/icons/
links:
  - url: https://google.com
    title: Google
  - url: https://google.com
    title: My Resume
    icon: paperclip
  - url: https://google.com
    title: My Portfolio
    icon: user-circle
  - url: https://google.com
    title: A really cool blog I like
    icon: false
  - url: https://google.com
    title: Cool Site

# disqus:
#   shortname: 

# Minimaless date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minimaless:
  date_format: "%b %-d, %Y"
preview_posts: true
permalink: /:title/
paginate: 2
paginate_path: "/page:num/"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - _pages/about.md
  - _pages/archive.md
  - _pages/baglantilar.md
  

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-paginate

markdown: kramdown
theme: minimaless

include:
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - tmp
